#!/usr/bin/env node
// Scaffold a species for the 3D battle gauntlet (see docs/POKEMON_PIPELINE.md).
//
//   node tools/gauntlet/new_species.mjs --slug swampert [--fetch] [--force]
//   node tools/gauntlet/new_species.mjs --slug swampert --dry [--model path.glb]
//
//   --fetch   download the pre-rigged model first (tools/models/fetch_model.mjs)
//   --dry     only print the guessed rig map
//   --model   read the skeleton from another .glb (with --dry)
//   --force   overwrite existing profile files
//
// Writes src/pokemon/<slug>/{rig.ts, poses.ts, clips.ts, index.ts,
// calibration.json} and registers the species in src/pokemon/registry.ts:
// a guessed semantic rig map, the bind pose as stance, the generic starter
// clips and a starting calibration scaled from the stock sprite. The species
// is then playable (?player=<slug>) and ready for calibration and authoring.

import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) args[a.slice(2)] = argv[i + 1] === undefined || argv[i + 1].startsWith('--') ? true : argv[++i];
  }
  return args;
}

/** Read the JSON chunk of a binary glTF. */
export function readGlbJson(buf) {
  if (buf.toString('ascii', 0, 4) !== 'glTF') throw new Error('not a .glb file');
  const len = buf.readUInt32LE(12);
  if (buf.toString('ascii', 16, 20) !== 'JSON') throw new Error('first .glb chunk is not JSON');
  return JSON.parse(buf.toString('utf8', 20, 20 + len));
}

/** "050 Head" -> "Head", "Waist_63" -> "Waist". */
export const normalize = (name) => name.replace(/^\d+\s+/, '').replace(/_\d+$/, '');

// Semantic name -> candidate joint names (first match wins). Game Freak's
// 3DS-era skeletons share these names across body plans.
const CENTER = {
  hips: ['Hips', 'Waist', 'Pelvis'],
  spine: ['Spine1', 'Spine'],
  chest: ['Spine2', 'Chest'],
  neck: ['Neck', 'Neck1'],
  head: ['Head'],
  jaw: ['Jaw', 'LowerBeak', 'LowerJaw'],
  tail: ['Tail', 'Tail1', 'TailA', 'TailA1', 'TailA01'],
};
const SIDED = {
  shoulder: ['Shoulder'],
  arm: ['Arm', 'UpperArm'],
  forearm: ['ForeArm'],
  hand: ['Hand'],
  thigh: ['Thigh'],
  shin: ['Leg'],
  foot: ['Foot'],
  toe: ['Toe', 'Toe1', 'ToeA', 'ToeA1'],
  ear: ['Ear', 'Ear1'],
  hair: ['Hair1', 'HairA1'],
  hairTip: ['Hair2', 'HairA2'],
};

export function guessRig(jointNames) {
  const byNorm = new Map();
  for (const n of jointNames) if (!byNorm.has(normalize(n))) byNorm.set(normalize(n), n);
  const bones = {};
  for (const [semantic, cands] of Object.entries(CENTER)) {
    const hit = cands.find((c) => byNorm.has(c));
    if (hit) bones[semantic] = byNorm.get(hit);
  }
  for (const [semantic, cands] of Object.entries(SIDED)) {
    for (const [side, pre] of [['L', 'L'], ['R', 'R']]) {
      const hit = cands.find((c) => byNorm.has(pre + c) || byNorm.has(`${c}_${side}`) || byNorm.has(`${c}${side}`));
      if (!hit) continue;
      bones[semantic + side] = byNorm.get(pre + hit) ?? byNorm.get(`${hit}_${side}`) ?? byNorm.get(`${hit}${side}`);
    }
  }
  const pelvisNodes = [bones.hips, bones.spine].filter(Boolean);
  const hasLegs = ['thigh', 'shin', 'foot'].every((k) => bones[`${k}L`] && bones[`${k}R`]);
  const legs = hasLegs
    ? { left: { thigh: 'thighL', shin: 'shinL', foot: 'footL' }, right: { thigh: 'thighR', shin: 'shinR', foot: 'footR' } }
    : undefined;
  const used = new Set(Object.values(bones));
  const unmapped = jointNames.filter((n) => !used.has(n));
  return { bones, pelvisNodes, legs, unmapped };
}

const wrap = (items, width = 76, indent = '//   ') => {
  const lines = [];
  let line = '';
  for (const it of items) {
    if ((line + ' ' + it).length > width) {
      lines.push(indent + line.trim());
      line = '';
    }
    line += ' ' + it;
  }
  if (line.trim()) lines.push(indent + line.trim());
  return lines.join('\n');
};

function rigTs(name, rig, joints) {
  const bones = Object.entries(rig.bones).map(([k, v]) => `    ${k}: '${v}',`).join('\n');
  const legs = rig.legs
    ? `\n  legs: {\n    left: { thigh: 'thighL', shin: 'shinL', foot: 'footL' },\n    right: { thigh: 'thighR', shin: 'shinR', foot: 'footR' },\n  },`
    : '';
  return `// ${name} rig map: semantic names -> skeleton joints. Generated by
// tools/gauntlet/new_species.mjs from the model's joint names; review it
// (docs/POKEMON_PIPELINE.md, "Rig map"). Semantic names ending in L/R mirror.
//
// Joints in the model:
${wrap(joints)}
//
// Not mapped (add semantic names when clips need them):
${wrap(rig.unmapped.length ? rig.unmapped : ['(none)'])}
import type { RigProfile } from '../../anim/rig';

export const RIG: RigProfile = {
  bones: {
${bones}
  },
  pelvisNodes: [${rig.pelvisNodes.map((n) => `'${n}'`).join(', ')}],${legs}
};
`;
}

function posesTs(name) {
  return `// ${name} poses. STANCE starts as the model's bind pose; shape it to the
// stock Emerald front sprite in the rig lab (?mode=riglab&species=<slug>).
// See src/pokemon/blaziken/poses.ts for the conventions (bones in model-axis
// degrees, aims as model-space directions, pelvis, plantFeet).
import type { Pose } from '../../anim/rig';

export const STANCE: Pose = {};
`;
}

function clipsTs(name) {
  return `// ${name} battle clips: the generic starter set until bespoke clips
// replace it (src/pokemon/blaziken/clips.ts is a finished reference set).
import type { Clip } from '../../anim/clip';
import { makeGenericClips } from '../generic/clips';
import { STANCE } from './poses';

export const CLIPS: Record<string, Clip> = makeGenericClips(STANCE);
`;
}

function indexTs(slug, name, effectHints) {
  const hints = effectHints.length
    ? `\n    // Candidate effect meshes/materials (fire, glow...): ${effectHints.join(', ')}\n    // List them here and bind them in \`effects\` to drive them from clips.`
    : '';
  return `import type { SpeciesProfile } from '../profile';
import { applyCalibration } from '../profile';
import { RIG } from './rig';
import { STANCE } from './poses';
import { CLIPS } from './clips';
import calibration from './calibration.json';

/** ${name}: generated by tools/gauntlet/new_species.mjs. */
export async function createProfile(palettes: { normal: SpeciesProfile['palette']; shiny: SpeciesProfile['palette'] }): Promise<SpeciesProfile> {
  const cal = calibration as SpeciesProfile['calibration'];
  return {
    slug: '${slug}',
    rig: RIG,
    poses: { stance: STANCE },
    clips: CLIPS,${hints}
    effectParts: [],
    effects: {},
    moveClips: {},
    palette: palettes.normal,
    shinyPalette: palettes.shiny,
    calibration: cal,
    placeInSlot: (root, slot) => applyCalibration(root, cal, slot),
  };
}
`;
}

async function register(slug) {
  const path = join(ROOT, 'src/pokemon/registry.ts');
  let src = await readFile(path, 'utf8');
  if (new RegExp(`^\\s+${slug}:`, 'm').test(src)) return false;
  src = src.replace(/(const FACTORIES[^{]*\{\n)/, `$1  ${slug}: async () => (await import('./${slug}')).createProfile,\n`);
  await writeFile(path, src);
  return true;
}

const args = parseArgs(process.argv.slice(2));
if (!args.slug) {
  console.error('usage: new_species.mjs --slug <species> [--fetch] [--force] [--dry [--model file.glb]]');
  process.exit(1);
}
const slug = String(args.slug).toLowerCase();
const species = JSON.parse(await readFile(join(ROOT, 'src/data/generated/species.json'), 'utf8'))[slug];
if (!species) {
  console.error(`unknown species "${slug}" (see src/data/generated/species.json)`);
  process.exit(1);
}

const modelPath = args.model ? resolve(String(args.model)) : join(ROOT, 'public/assets/pokemon', slug, 'model.glb');
if (args.fetch && !args.model) {
  const r = spawnSync(process.execPath, [join(ROOT, 'tools/models/fetch_model.mjs'), '--dex', String(species.nationalDex), '--slug', slug], {
    stdio: 'inherit',
    env: { ...process.env, NODE_USE_ENV_PROXY: '1' },
  });
  if (r.status !== 0) process.exit(r.status ?? 1);
}
if (!existsSync(modelPath)) {
  console.error(`no model at ${modelPath}; run with --fetch (national dex #${species.nationalDex})`);
  process.exit(1);
}

const gltf = readGlbJson(await readFile(modelPath));
const joints = (gltf.skins?.[0]?.joints ?? []).map((i) => gltf.nodes[i].name).filter(Boolean);
const rig = guessRig(joints);
const names = [...(gltf.meshes ?? []).map((m) => m.name), ...(gltf.materials ?? []).map((m) => m.name)].filter(Boolean);
const effectHints = [...new Set(names.filter((n) => /fire|flame|glow|aura|sten|light/i.test(n)))];

console.log(`${species.name} (#${species.nationalDex}): ${joints.length} joints`);
for (const [k, v] of Object.entries(rig.bones)) console.log(`  ${k.padEnd(10)} -> ${v}`);
console.log(`  legs IK: ${rig.legs ? 'yes' : 'no'}; unmapped: ${rig.unmapped.length}`);
if (effectHints.length) console.log(`  effect candidates: ${effectHints.join(', ')}`);
if (args.dry) process.exit(0);

const dir = join(ROOT, 'src/pokemon', slug);
if (existsSync(join(dir, 'index.ts')) && !args.force) {
  console.error(`src/pokemon/${slug} already exists (use --force to overwrite)`);
  process.exit(1);
}
await mkdir(dir, { recursive: true });

// Starting calibration: Blaziken's, with the height scaled by the stock
// sprites' visible heights. tools/calibrate/run.mjs refines it.
const ref = JSON.parse(await readFile(join(ROOT, 'src/pokemon/blaziken/calibration.json'), 'utf8'));
const refSpecies = JSON.parse(await readFile(join(ROOT, 'src/data/generated/species.json'), 'utf8')).blaziken;
const calibration = {
  height: +(ref.height * (species.frontCoords.height / refSpecies.frontCoords.height)).toFixed(4),
  slots: {
    enemy: { yaw: 0, dx: 0, dz: 0, lift: 0 },
    player: { yaw: 30, dx: 0, dz: 0, lift: 0 },
  },
  outline: ref.outline,
  grade: ref.grade,
};

await writeFile(join(dir, 'rig.ts'), rigTs(species.name, rig, joints));
await writeFile(join(dir, 'poses.ts'), posesTs(species.name));
await writeFile(join(dir, 'clips.ts'), clipsTs(species.name));
await writeFile(join(dir, 'index.ts'), indexTs(slug, species.name, effectHints));
await writeFile(join(dir, 'calibration.json'), JSON.stringify(calibration, null, 2) + '\n');
const registered = await register(slug);
console.log(`wrote src/pokemon/${slug}/ (rig, poses, clips, index, calibration)${registered ? ' and registered it' : ''}`);
console.log(`next: node tools/calibrate/run.mjs --species ${slug}  (then --phase color); see docs/POKEMON_PIPELINE.md`);
