#!/usr/bin/env node
// Scaffold a species for the 3D battle gauntlet (see docs/POKEMON_PIPELINE.md).
//
//   node tools/gauntlet/new_species.mjs --slug swampert [--fetch] [--force]
//   node tools/gauntlet/new_species.mjs --slug swampert --dry [--model path.glb]
//
//   --fetch   download the pre-rigged model first (tools/models/fetch_model.mjs)
//   --dry     only print the guessed rig map
//   --model   read the skeleton from another .glb (with --dry)
//   --force   overwrite existing profile files
//
// Writes src/pokemon/<slug>/{rig.ts, poses.ts, clips.ts, index.ts,
// calibration.json} and registers the species in src/pokemon/registry.ts:
// a guessed semantic rig map, the bind pose as stance, the generic starter
// clips and a starting calibration scaled from the stock sprite. The species
// is then playable (?player=<slug>) and ready for calibration and authoring.

import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { guessRig, looksQuadruped, readGlbJson } from './rigmap.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) args[a.slice(2)] = argv[i + 1] === undefined || argv[i + 1].startsWith('--') ? true : argv[++i];
  }
  return args;
}

const wrap = (items, width = 76, indent = '//   ') => {
  const lines = [];
  let line = '';
  for (const it of items) {
    if ((line + ' ' + it).length > width) {
      lines.push(indent + line.trim());
      line = '';
    }
    line += ' ' + it;
  }
  if (line.trim()) lines.push(indent + line.trim());
  return lines.join('\n');
};

function rigTs(name, rig, joints, quadruped) {
  const bones = Object.entries(rig.bones).map(([k, v]) => `    ${k}: '${v}',`).join('\n');
  let legs = rig.legs
    ? `\n  legs: {\n    left: { thigh: 'thighL', shin: 'shinL', foot: 'footL' },\n    right: { thigh: 'thighR', shin: 'shinR', foot: 'footR' },\n  },`
    : '';
  if (quadruped) {
    legs += `\n  // Walks on all fours: the front legs are planted too (elbows bend back).\n  frontLegs: {\n    left: { thigh: 'armL', shin: 'forearmL', foot: 'handL', bend: -1 },\n    right: { thigh: 'armR', shin: 'forearmR', foot: 'handR', bend: -1 },\n  },`;
  }
  return `// ${name} rig map: semantic names -> skeleton joints. Generated by
// tools/gauntlet/new_species.mjs from the model's joint names; review it
// (docs/POKEMON_PIPELINE.md, "Rig map"). Semantic names ending in L/R mirror.
//
// Joints in the model:
${wrap(joints)}
//
// Not mapped (add semantic names when clips need them):
${wrap(rig.unmapped.length ? rig.unmapped : ['(none)'])}
import type { RigProfile } from '../../anim/rig';

export const RIG: RigProfile = {
  bones: {
${bones}
  },
  pelvisNodes: [${rig.pelvisNodes.map((n) => `'${n}'`).join(', ')}],${legs}
};
`;
}

function posesTs(name) {
  return `// ${name} poses. STANCE starts as the model's bind pose; shape it to the
// stock Emerald front sprite in the rig lab (?mode=riglab&species=<slug>).
// See src/pokemon/blaziken/poses.ts for the conventions (bones in model-axis
// degrees, aims as model-space directions, pelvis, plantFeet).
import type { Pose } from '../../anim/rig';

export const STANCE: Pose = {};
`;
}

function clipsTs(name) {
  return `// ${name} battle clips: the generic starter set until bespoke clips
// replace it (src/pokemon/blaziken/clips.ts is a finished reference set).
import type { Clip } from '../../anim/clip';
import { makeGenericClips } from '../generic/clips';
import { STANCE } from './poses';

export const CLIPS: Record<string, Clip> = makeGenericClips(STANCE);
`;
}

function indexTs(slug, name, effectHints, bodyPlan, showcase) {
  const hints = effectHints.length
    ? `\n    // Candidate effect meshes/materials (fire, glow...): ${effectHints.join(', ')}\n    // List them here and bind them in \`effects\` to drive them from clips.`
    : '';
  return `import type { SpeciesProfile } from '../profile';
import { applyCalibration } from '../profile';
import { RIG } from './rig';
import { STANCE } from './poses';
import { CLIPS } from './clips';
import calibration from './calibration.json';

/** ${name}: generated by tools/gauntlet/new_species.mjs. */
export async function createProfile(palettes: { normal: SpeciesProfile['palette']; shiny: SpeciesProfile['palette'] }): Promise<SpeciesProfile> {
  const cal = calibration as SpeciesProfile['calibration'];
  return {
    slug: '${slug}',
    rig: RIG,
    poses: { stance: STANCE },
    clips: CLIPS,${hints}
    effectParts: [],
    effects: {},
    // The species brief (see .claude/skills/pokemon-gauntlet): fill in from
    // node tools/gauntlet/brief.mjs --slug ${slug} and the stock sprites.
    brief: {
      bodyPlan: '${bodyPlan}',
      character: 'TODO: how it moves and fights (weight, temperament, habits)',
      powerSource: 'TODO: where its type power comes from (mouth, cannons, flower...)',
    },
    // Effect origins besides mouth/eyes/hands/feet/body, e.g.
    // cannons: { bones: ['cannonL', 'cannonR'] }, and which motif uses which.
    emitters: {},
    emitterFor: {},
    // Loose parts on springs, e.g. { bones: ['tail'], damping: 0.2, elasticity: 0.1, maxDrift: 0.45 }.
    dynamics: [],
    moveClips: {},
    motifClips: {},
    // Mesh/node name fragments to hide (extra LODs, alternate meshes).
    hiddenParts: [],
    showcaseMoves: ${JSON.stringify(showcase)},
    palette: palettes.normal,
    shinyPalette: palettes.shiny,
    calibration: cal,
    placeInSlot: (root, slot) => applyCalibration(root, cal, slot),
  };
}
`;
}

async function register(slug) {
  const path = join(ROOT, 'src/pokemon/registry.ts');
  let src = await readFile(path, 'utf8');
  if (new RegExp(`^\\s+${slug}:`, 'm').test(src)) return false;
  src = src.replace(/(const FACTORIES[^{]*\{\n)/, `$1  ${slug}: async () => (await import('./${slug}')).createProfile,\n`);
  await writeFile(path, src);
  return true;
}

const args = parseArgs(process.argv.slice(2));
if (!args.slug) {
  console.error('usage: new_species.mjs --slug <species> [--fetch] [--force] [--dry [--model file.glb]]');
  process.exit(1);
}
const slug = String(args.slug).toLowerCase();
const species = JSON.parse(await readFile(join(ROOT, 'src/data/generated/species.json'), 'utf8'))[slug];
if (!species) {
  console.error(`unknown species "${slug}" (see src/data/generated/species.json)`);
  process.exit(1);
}

const modelPath = args.model ? resolve(String(args.model)) : join(ROOT, 'public/assets/pokemon', slug, 'model.glb');
if (args.fetch && !args.model) {
  const r = spawnSync(process.execPath, [join(ROOT, 'tools/models/fetch_model.mjs'), '--dex', String(species.nationalDex), '--slug', slug], {
    stdio: 'inherit',
    env: { ...process.env, NODE_USE_ENV_PROXY: '1' },
  });
  if (r.status !== 0) process.exit(r.status ?? 1);
}
if (!existsSync(modelPath)) {
  console.error(`no model at ${modelPath}; run with --fetch (national dex #${species.nationalDex})`);
  process.exit(1);
}

const gltf = readGlbJson(await readFile(modelPath));
const joints = (gltf.skins?.[0]?.joints ?? []).map((i) => gltf.nodes[i].name).filter(Boolean);
const rig = guessRig(joints);
const quadruped = looksQuadruped(gltf, rig.bones);
// Starting showcase: the Gen 3 wild moveset at level 50 (last four level-up moves).
const showcase = [...new Set(species.learnset.filter((l) => l.level <= 50).map((l) => l.move))].slice(-4).map((m) => m.replace('MOVE_', ''));
const names = [...(gltf.meshes ?? []).map((m) => m.name), ...(gltf.materials ?? []).map((m) => m.name)].filter(Boolean);
const effectHints = [...new Set(names.filter((n) => /fire|flame|glow|aura|sten|light/i.test(n)))];

console.log(`${species.name} (#${species.nationalDex}): ${joints.length} joints`);
for (const [k, v] of Object.entries(rig.bones)) console.log(`  ${k.padEnd(10)} -> ${v}`);
console.log(`  legs IK: ${rig.legs ? 'yes' : 'no'}; body plan: ${quadruped ? 'quadruped (front legs planted)' : 'biped'}; unmapped: ${rig.unmapped.length}`);
if (effectHints.length) console.log(`  effect candidates: ${effectHints.join(', ')}`);
if (args.dry) process.exit(0);

const dir = join(ROOT, 'src/pokemon', slug);
if (existsSync(join(dir, 'index.ts')) && !args.force) {
  console.error(`src/pokemon/${slug} already exists (use --force to overwrite)`);
  process.exit(1);
}
await mkdir(dir, { recursive: true });

// Starting calibration: Blaziken's, with the height scaled by the stock
// sprites' visible heights. tools/calibrate/run.mjs refines it.
const ref = JSON.parse(await readFile(join(ROOT, 'src/pokemon/blaziken/calibration.json'), 'utf8'));
const refSpecies = JSON.parse(await readFile(join(ROOT, 'src/data/generated/species.json'), 'utf8')).blaziken;
const calibration = {
  height: +(ref.height * (species.frontCoords.height / refSpecies.frontCoords.height)).toFixed(4),
  slots: {
    enemy: { yaw: 0, dx: 0, dz: 0, lift: 0 },
    player: { yaw: 30, dx: 0, dz: 0, lift: 0 },
  },
  outline: ref.outline,
  grade: ref.grade,
};

await writeFile(join(dir, 'rig.ts'), rigTs(species.name, rig, joints, quadruped));
await writeFile(join(dir, 'poses.ts'), posesTs(species.name));
await writeFile(join(dir, 'clips.ts'), clipsTs(species.name));
await writeFile(join(dir, 'index.ts'), indexTs(slug, species.name, effectHints, quadruped ? 'quadruped' : 'biped', showcase));
const template = join(ROOT, '.claude/skills/pokemon-gauntlet/REVIEW_TEMPLATE.md');
if (existsSync(template)) {
  await writeFile(join(dir, 'REVIEW.md'), (await readFile(template, 'utf8')).replaceAll('<Species>', species.name.charAt(0) + species.name.slice(1).toLowerCase()).replaceAll('<slug>', slug));
}
await writeFile(join(dir, 'calibration.json'), JSON.stringify(calibration, null, 2) + '\n');
const registered = await register(slug);
console.log(`wrote src/pokemon/${slug}/ (rig, poses, clips, index, calibration, REVIEW.md)${registered ? ' and registered it' : ''}`);
console.log(`next: node tools/calibrate/run.mjs --species ${slug}  (then --phase color); see docs/POKEMON_PIPELINE.md`);
